branches:
  only:
    - master
language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
before_script:
  - redis-cli ping

script:
  - nosetests
  - coverage run test_server.py
  - behave

after_success:
  - codecov

services:
  - redis-server
